version: "3.8"
services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  app:
    build:
      context: ./server
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mailhog
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/testdb
      MAILHOG_HOST: mailhog
